github:
  description: "Apache Sling Whiteboard - testing ground for new ideas"
  labels:
  - "java"
  - "sling"
  - "experimental"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
  dependabot_alerts: false
  dependabot_updates: false
notifications:
  jira_options: "link"
  pullrequests_bot_sonarcloud: "commits@sling.apache.org"
